; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:nucleo_f446re]
platform = ststm32
board = nucleo_f446re
framework = arduino
build_flags = 
    -D ENABLE_HWSERIAL1
    -DSDFAT_FILE_TYPE=1
    -DUSE_SPI_ARRAY_TRANSFER=0

lib_deps =
    # Specify libraries by name from the PlatformIO Registry (examples below)
    # Adafruit GFX Library
    # ESP32 BLE Arduino
    # You can also specify specific versions or a Git URL
    # MyPrivateLibrary@1.2.0
    # https://github.com
    # https://github.com/CuriousScientist0/ADS1256
    # Rob Rillaart's HX711 Library
    https://github.com/RobTillaart/HX711

    # SD card library "SdFAT"
    greiman/SdFat @ ^2.2.0